# Weaviate stuff
# get info about current Weaviate instance
GET http://localhost:8080/v1/meta

###
# Is weaviate live?
GET http://localhost:8080/v1/.well-known/live

###
# check weaviate nodes' health
curl http://localhost:8080/v1/nodes

###
# get all objects in Weaviate
GET http://localhost:8080/v1/objects

###
# get Weaviate schema
GET http://localhost:8080/v1/schema

###
# create a Document
POST http://localhost:8080/v1/objects
Content-Type: application/json

{
  "class": "Document",
  "properties": {
    "name": "hello.txt",
    "content_type": "text",
    "content": "Hello world!"
  }
}

###
# delete a Document
DELETE  http://localhost:8080/v1/objects/Document/010750a4-aaf0-4ab9-9191-e4fe189cdce0

###
# get the content and vector representation of all Documents
POST http://localhost:8080/v1/graphql
X-Request-Type: GraphQL
Content-Type: application/json

query {
  Get {
    Document {
        context
        _additional {
          vector
          id
        }
    }
  }
}

###
# ask a question
POST http://localhost:8080/v1/graphql
X-Request-Type: GraphQL
Content-Type: application/json

query {
  Get {
    Document(
      ask: {
        question: "What do professional athletes seek to boost from breathing oxygen?",
        properties: ["context"]
      },
      limit: 5
    ) {
      context
      _additional {
        answer {
          hasAnswer
          result
        }
      }
    }
  }
}